name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test RustBam on Ubuntu with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-pip cargo

      - name: Install test dependencies
        run: pip install pytest coverage maturin

      - name: Build and Install RustBam
        run: |
          maturin develop

      - name: Verify RustBam CLI
        run: rustbam --help

      - name: Run Tests with Coverage
        run: |
          coverage run -m pytest -v
          coverage report -m
          coverage xml

      - name: Make Coverage Badge
        uses: action-badges/cobertura-coverage-xml-badges@0.3.1
        with:
          file-name: coverage.svg
          badge-branch: badges
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: coverage.xml

      - name: Commit Coverage Badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add coverage.svg
          git commit -m "add coverage badge"
          git push
        continue-on-error: true  # Avoid failure if nothing to commit

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

